-- Generated by `pnpm db:snapshot` — do not edit by hand.
-- Rebuilt from ./drizzle migrations + db/seed.sql; restored into the
-- docker-compose instance on first boot via /docker-entrypoint-initdb.d
-- (run `pnpm db:reset` after regenerating to pick it up).

--
-- PostgreSQL database dump
--

\restrict EXu4sE4Xbry1KaYdUQ2JM3oxHNTUGoTUcCPMcz5eRNQ1hB9Pc2D5Vwr43wjHEAP

-- Dumped from database version 16.14
-- Dumped by pg_dump version 16.14

SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;

--
-- Name: identity_registry; Type: SCHEMA; Schema: -; Owner: -
--

CREATE SCHEMA identity_registry;


--
-- Name: tcg; Type: SCHEMA; Schema: -; Owner: -
--

CREATE SCHEMA tcg;


SET default_tablespace = '';

SET default_table_access_method = heap;

--
-- Name: control; Type: TABLE; Schema: identity_registry; Owner: -
--

CREATE TABLE identity_registry.control (
    schema_name text NOT NULL,
    state text DEFAULT 'idle'::text NOT NULL,
    lock_token uuid,
    locked_by text,
    locked_at timestamp with time zone,
    CONSTRAINT control_state_check CHECK ((state = ANY (ARRAY['idle'::text, 'migrating'::text])))
);


--
-- Name: migrations; Type: TABLE; Schema: identity_registry; Owner: -
--

CREATE TABLE identity_registry.migrations (
    schema_name text NOT NULL,
    name text NOT NULL,
    applied_at timestamp with time zone DEFAULT now() NOT NULL
);


--
-- Name: objects; Type: TABLE; Schema: identity_registry; Owner: -
--

CREATE TABLE identity_registry.objects (
    logical_id uuid NOT NULL,
    kind text NOT NULL,
    schema_name text NOT NULL,
    table_name text NOT NULL,
    column_name text,
    table_oid oid NOT NULL,
    attnum smallint,
    dropped_at timestamp with time zone,
    created_at timestamp with time zone DEFAULT now() NOT NULL,
    updated_at timestamp with time zone DEFAULT now() NOT NULL,
    CONSTRAINT objects_check CHECK (((kind = 'table'::text) = (column_name IS NULL))),
    CONSTRAINT objects_check1 CHECK (((kind = 'table'::text) = (attnum IS NULL))),
    CONSTRAINT objects_kind_check CHECK ((kind = ANY (ARRAY['table'::text, 'column'::text])))
);


--
-- Name: card; Type: TABLE; Schema: tcg; Owner: -
--

CREATE TABLE tcg.card (
    id bigint NOT NULL,
    name text NOT NULL,
    collector_number text NOT NULL,
    set_identifier text NOT NULL
);


--
-- Name: TABLE card; Type: COMMENT; Schema: tcg; Owner: -
--

COMMENT ON TABLE tcg.card IS 'logical_id=86b4485c-391c-4615-8fe5-49ab9b2603e7';


--
-- Name: COLUMN card.id; Type: COMMENT; Schema: tcg; Owner: -
--

COMMENT ON COLUMN tcg.card.id IS 'logical_id=b30e5cdb-2fc3-496c-b331-6f8e633e1b50';


--
-- Name: COLUMN card.name; Type: COMMENT; Schema: tcg; Owner: -
--

COMMENT ON COLUMN tcg.card.name IS 'logical_id=82c9838d-df66-4b25-a03b-64b81305c35e';


--
-- Name: COLUMN card.collector_number; Type: COMMENT; Schema: tcg; Owner: -
--

COMMENT ON COLUMN tcg.card.collector_number IS 'logical_id=e0056a68-a0b4-40ad-80a2-93b366889ae3';


--
-- Name: COLUMN card.set_identifier; Type: COMMENT; Schema: tcg; Owner: -
--

COMMENT ON COLUMN tcg.card.set_identifier IS 'logical_id=1aa50852-fadd-456a-a483-64128cd5ff54';


--
-- Name: card_id_seq; Type: SEQUENCE; Schema: tcg; Owner: -
--

ALTER TABLE tcg.card ALTER COLUMN id ADD GENERATED ALWAYS AS IDENTITY (
    SEQUENCE NAME tcg.card_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Data for Name: control; Type: TABLE DATA; Schema: identity_registry; Owner: -
--

COPY identity_registry.control (schema_name, state, lock_token, locked_by, locked_at) FROM stdin;
tcg	idle	\N	\N	\N
\.


--
-- Data for Name: migrations; Type: TABLE DATA; Schema: identity_registry; Owner: -
--

COPY identity_registry.migrations (schema_name, name, applied_at) FROM stdin;
tcg	0000_create_card	2026-08-04 10:01:39.287617+00
\.


--
-- Data for Name: objects; Type: TABLE DATA; Schema: identity_registry; Owner: -
--

COPY identity_registry.objects (logical_id, kind, schema_name, table_name, column_name, table_oid, attnum, dropped_at, created_at, updated_at) FROM stdin;
86b4485c-391c-4615-8fe5-49ab9b2603e7	table	tcg	card	\N	17255	\N	\N	2026-08-04 10:01:39.287617+00	2026-08-04 10:01:39.287617+00
b30e5cdb-2fc3-496c-b331-6f8e633e1b50	column	tcg	card	id	17255	1	\N	2026-08-04 10:01:39.287617+00	2026-08-04 10:01:39.287617+00
82c9838d-df66-4b25-a03b-64b81305c35e	column	tcg	card	name	17255	2	\N	2026-08-04 10:01:39.287617+00	2026-08-04 10:01:39.287617+00
e0056a68-a0b4-40ad-80a2-93b366889ae3	column	tcg	card	collector_number	17255	3	\N	2026-08-04 10:01:39.287617+00	2026-08-04 10:01:39.287617+00
1aa50852-fadd-456a-a483-64128cd5ff54	column	tcg	card	set_identifier	17255	4	\N	2026-08-04 10:01:39.287617+00	2026-08-04 10:01:39.287617+00
\.


--
-- Data for Name: card; Type: TABLE DATA; Schema: tcg; Owner: -
--

COPY tcg.card (id, name, collector_number, set_identifier) FROM stdin;
1	Lightning Bolt	161	lea
2	Counterspell	54	lea
3	Serra Angel	39	lea
4	Llanowar Elves	314	m19
5	Shivan Dragon	180	m20
\.


--
-- Name: card_id_seq; Type: SEQUENCE SET; Schema: tcg; Owner: -
--

SELECT pg_catalog.setval('tcg.card_id_seq', 5, true);


--
-- Name: control control_pkey; Type: CONSTRAINT; Schema: identity_registry; Owner: -
--

ALTER TABLE ONLY identity_registry.control
    ADD CONSTRAINT control_pkey PRIMARY KEY (schema_name);


--
-- Name: migrations migrations_pkey; Type: CONSTRAINT; Schema: identity_registry; Owner: -
--

ALTER TABLE ONLY identity_registry.migrations
    ADD CONSTRAINT migrations_pkey PRIMARY KEY (schema_name, name);


--
-- Name: objects objects_pkey; Type: CONSTRAINT; Schema: identity_registry; Owner: -
--

ALTER TABLE ONLY identity_registry.objects
    ADD CONSTRAINT objects_pkey PRIMARY KEY (logical_id, schema_name);


--
-- Name: card card_pkey; Type: CONSTRAINT; Schema: tcg; Owner: -
--

ALTER TABLE ONLY tcg.card
    ADD CONSTRAINT card_pkey PRIMARY KEY (id);


--
-- Name: objects_live_name_uq; Type: INDEX; Schema: identity_registry; Owner: -
--

CREATE UNIQUE INDEX objects_live_name_uq ON identity_registry.objects USING btree (schema_name, table_name, COALESCE(column_name, ''::text)) WHERE (dropped_at IS NULL);


--
-- Name: card_set_collector_idx; Type: INDEX; Schema: tcg; Owner: -
--

CREATE UNIQUE INDEX card_set_collector_idx ON tcg.card USING btree (set_identifier, collector_number);


--
-- PostgreSQL database dump complete
--

\unrestrict EXu4sE4Xbry1KaYdUQ2JM3oxHNTUGoTUcCPMcz5eRNQ1hB9Pc2D5Vwr43wjHEAP


-- Re-anchor catalog identities after restore: oids/attnums are per-database.
UPDATE identity_registry.objects o
SET table_oid = c.oid
FROM pg_class c JOIN pg_namespace n ON n.oid = c.relnamespace
WHERE o.dropped_at IS NULL
  AND n.nspname = o.schema_name AND c.relname = o.table_name;

UPDATE identity_registry.objects o
SET attnum = a.attnum
FROM pg_attribute a
WHERE o.kind = 'column' AND o.dropped_at IS NULL
  AND a.attrelid = o.table_oid AND a.attname = o.column_name
  AND NOT a.attisdropped;
