import { execFileSync } from "node:child_process";
import fs from "node:fs";
import path from "node:path";
import pg from "pg";
import { bootstrap, ident } from "../src/registry.js";
import { applyMigrations, loadDrizzleMigrations } from "../src/migrate.js";

// Bake the drizzle migrations + seed data into a committed, human-readable
// pg_dump that docker-compose restores on first boot (via
// /docker-entrypoint-initdb.d). The dump captures everything a fresh apply
// would produce — the tenant schema, its rows, AND the identity_registry
// bookkeeping (logical_ids, applied-migration markers) — so a restored
// database picks up exactly where the snapshot left off: new migrations
// apply incrementally, already-baked ones are skipped.
//
//   pnpm db:snapshot   (requires the docker instance: pnpm db:up)
//   pnpm db:reset      (recreate the container so the new dump is restored)
//
// Note: logical_ids are minted at apply time (randomUUID), so regenerating
// the snapshot re-mints them — the diff churn in db/init/testdb.sql is
// expected. Within one committed snapshot the ids are stable across every
// restore, which is what makes the baked image inspectable and reproducible.

const BASE =
  process.env.DATABASE_URL_BASE ?? "postgres://postgres:postgres@127.0.0.1:54329";
const SCHEMA = "tcg";
const BUILD_DB = "snapshot_build";
const OUT = path.join("db", "init", "testdb.sql");

const admin = new pg.Pool({ connectionString: `${BASE}/postgres`, max: 1 });
try {
  // Build in a scratch database so the dump never picks up test leftovers
  // from the shared postgres database.
  await admin.query(`DROP DATABASE IF EXISTS ${BUILD_DB} WITH (FORCE)`);
  await admin.query(`CREATE DATABASE ${BUILD_DB}`);

  const build = new pg.Pool({ connectionString: `${BASE}/${BUILD_DB}`, max: 2 });
  try {
    await bootstrap(build);
    const migrations = loadDrizzleMigrations("drizzle");
    console.log(`Applying ${migrations.length} migration(s) to schema "${SCHEMA}"`);
    const results = await applyMigrations(build, { schema: SCHEMA, migrations });
    for (const r of results) {
      const { registered, healed, tombstoned } = r.sync;
      console.log(
        `- ${r.name}: registered ${registered.tables} table(s) / ` +
          `${registered.columns} column(s), healed ${healed}, tombstoned ${tombstoned}`,
      );
    }

    const seed = fs.readFileSync(path.join("db", "seed.sql"), "utf8");
    const c = await build.connect();
    try {
      await c.query("BEGIN");
      await c.query(`SET LOCAL search_path TO ${ident(SCHEMA)}`);
      await c.query(seed);
      await c.query("COMMIT");
    } catch (err) {
      await c.query("ROLLBACK").catch(() => {});
      throw err;
    } finally {
      c.release();
    }
    console.log("Seeded db/seed.sql");
  } finally {
    await build.end();
  }

  const dump = execFileSync(
    "docker",
    ["compose", "exec", "-T", "postgres",
     "pg_dump", "-U", "postgres", "-d", BUILD_DB, "--no-owner", "--no-privileges"],
    { encoding: "utf8", maxBuffer: 64 * 1024 * 1024 },
  );
  const header =
    "-- Generated by `pnpm db:snapshot` — do not edit by hand.\n" +
    "-- Rebuilt from ./drizzle migrations + db/seed.sql; restored into the\n" +
    "-- docker-compose instance on first boot via /docker-entrypoint-initdb.d\n" +
    "-- (run `pnpm db:reset` after regenerating to pick it up).\n\n";
  // Physical identity (oid/attnum) is per-database and does not survive a
  // dump/restore — the same reason importSchema() re-anchors. The dump's
  // names are consistent with its registry rows by construction, so the
  // restored database re-resolves each live row's anchors by name.
  const reanchor = `
-- Re-anchor catalog identities after restore: oids/attnums are per-database.
UPDATE identity_registry.objects o
SET table_oid = c.oid
FROM pg_class c JOIN pg_namespace n ON n.oid = c.relnamespace
WHERE o.dropped_at IS NULL
  AND n.nspname = o.schema_name AND c.relname = o.table_name;

UPDATE identity_registry.objects o
SET attnum = a.attnum
FROM pg_attribute a
WHERE o.kind = 'column' AND o.dropped_at IS NULL
  AND a.attrelid = o.table_oid AND a.attname = o.column_name
  AND NOT a.attisdropped;
`;
  fs.mkdirSync(path.dirname(OUT), { recursive: true });
  fs.writeFileSync(OUT, header + dump + reanchor);
  console.log(`Wrote ${OUT} (${dump.length} bytes)`);

  await admin.query(`DROP DATABASE ${BUILD_DB} WITH (FORCE)`);
} finally {
  await admin.end();
}
